# Generated by Django 2.2.1 on 2019-05-20 22:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rides', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='api_key',
            field=models.CharField(max_length=100),
        ),
    ]
