# Generated by Django 2.2.1 on 2019-05-20 23:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rides', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='RidePassengers',
            new_name='RidePassenger',
        ),
    ]
