# Generated by Django 2.2.1 on 2019-05-20 22:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rides', '0002_auto_20190520_2217'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='city',
            options={'managed': True},
        ),
        migrations.AlterModelTable(
            name='city',
            table='rides_city',
        ),
    ]
