# Generated by Django 2.2.1 on 2019-05-21 00:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rides', '0002_auto_20190520_2303'),
        ('rides', '0003_auto_20190520_2233'),
    ]

    operations = [
    ]
