# Generated by Django 2.2.1 on 2019-05-21 00:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rides', '0004_merge_20190521_0012'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ride',
            name='end_city',
        ),
        migrations.RemoveField(
            model_name='ride',
            name='start_city',
        ),
        migrations.DeleteModel(
            name='City',
        ),
    ]
