# Generated by Django 2.2.1 on 2019-05-23 06:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rides', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ride',
            name='departure_time',
            field=models.DateField(),
        ),
    ]
