# Generated by Django 2.2.1 on 2019-05-27 21:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rides', '0002_auto_20190523_0629'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='phone_number',
        ),
        migrations.AlterField(
            model_name='request',
            name='status',
            field=models.CharField(default='pending', max_length=100),
        ),
    ]
